python CSPCargaBUS.py ./CSP-tests/alumnos1
python CSPCargaBUS.py ./CSP-tests/alumnos2
python CSPCargaBUS.py ./CSP-tests/alumnos3
python CSPCargaBUS.py ./CSP-tests/alumnos4
python CSPCargaBUS.py ./CSP-tests/alumnos5
python CSPCargaBUS.py ./CSP-tests/alumnos6
python CSPCargaBUS.py ./CSP-tests/alumnos7
python CSPCargaBUS.py ./CSP-tests/alumnos8
python CSPCargaBUS.py ./CSP-tests/alumnos9
python CSPCargaBUS.py ./CSP-tests/alumnos10
