python ASTARColaBus.py ./ASTAR-tests/alumnos1.prob 1
python ASTARColaBus.py ./ASTAR-tests/alumnos1.prob 2
python ASTARColaBus.py ./ASTAR-tests/alumnos2.prob 1
python ASTARColaBus.py ./ASTAR-tests/alumnos2.prob 2
python ASTARColaBus.py ./ASTAR-tests/alumnos3.prob 1
python ASTARColaBus.py ./ASTAR-tests/alumnos3.prob 2
python ASTARColaBus.py ./ASTAR-tests/alumnos4.prob 1
python ASTARColaBus.py ./ASTAR-tests/alumnos4.prob 2
python ASTARColaBus.py ./ASTAR-tests/alumnos5.prob 1
python ASTARColaBus.py ./ASTAR-tests/alumnos5.prob 2
python ASTARColaBus.py ./ASTAR-tests/alumnos6.prob 1
python ASTARColaBus.py ./ASTAR-tests/alumnos6.prob 2
python ASTARColaBus.py ./ASTAR-tests/alumnos7.prob 1
python ASTARColaBus.py ./ASTAR-tests/alumnos7.prob 2
